# Base configuration
permalink: /:title

# When using this template with a project page set the baseurl to '/project-name'
# For user/organization pages set this to an empty string
# When working locally use jekyll serve --baseurl '' so that you can view everything at localhost:4000
# See http://jekyllrb.com/docs/github-pages/ for more info
baseurl: '/DragonSlayers-I'

# Google Analytics
ga:
  root: 'himedlooff.github.io'
  id: 'UA-46767514-1'