# See http://jekyllrb.com/docs/github-pages/ for more info
baseurl: '/DragonSlayers-I'
baseurlremote:  '/DragonSlayers-I'
assetsurl:      'assets/'

# Google Analytics
ga:
  root: 'himedlooff.github.io'
  id: 'UA-46767514-1'